### ISSUE TITLE
Revise HttpRequestFunctionConfiguration configuration in favor of auto-configured by Spring Boot WebClient.Builder

### ISSUE THREAD

**Issue by artembilan** [spring-cloud/stream-applications#286]
Currently we have a bean in the `HttpRequestFunctionConfiguration` like:
```
	@Bean
	@ConditionalOnMissingBean(WebClient.class)
	public WebClient webClient(HttpRequestFunctionProperties properties,
			ObjectProvider<WebClientCustomizer> customizerProvider) {

		WebClient.Builder builder =
				WebClient.builder()
						.codecs((clientCodecConfigurer) ->
								clientCodecConfigurer.defaultCodecs()
										.maxInMemorySize(properties.getMaximumBufferSize()));
		customizerProvider.orderedStream().forEach((customizer) -> customizer.customize(builder));
		return builder.build();
	}
```

The Spring Boot provides for us a `WebClient.Builder` auto-configuration, including those `WebClientCustomizer` s:
```
	@Bean
	@Scope("prototype")
	@ConditionalOnMissingBean
	public WebClient.Builder webClientBuilder(ObjectProvider<WebClientCustomizer> customizerProvider) {
		WebClient.Builder builder = WebClient.builder();
		customizerProvider.orderedStream().forEach((customizer) -> customizer.customize(builder));
		return builder;
	}
```

That `maxInMemorySize` property is also auto-configured by the `DefaultCodecsConfiguration`  via `CodecProperties`:
```

	/**
	 * Limit on the number of bytes that can be buffered whenever the input stream needs
	 * to be aggregated. This applies only to the auto-configured WebFlux server and
	 * WebClient instances. By default this is not set, in which case individual codec
	 * defaults apply. Most codecs are limited to 256K by default.
	 */
	private DataSize maxInMemorySize;
```

So, we can get rid of our `HttpRequestFunctionProperties.maximumBufferSize` and use already auto-configured  `WebClient.Builder` as a dependency in the `httpRequestFunction` bean definition.

**Comment by sunny151091** [comment]
Hey @artembilan I am interested in contributing - could you give me any useful pointers to be able to pick this issue up? 
I am new to this so can you guide me on where should I start?

**Comment by onobc** [comment]
Hi @sunny151091 

I am not @artembilan  but I can give you some info to get you going as well 😄 

So... regardless of the change being made, you will want to be able to [build/test locally](https://github.com/spring-cloud/stream-applications/blob/main/README.adoc#build). From that point on it will look like something like the following:
1. Run the tests that are related to the area being changed - watch them pass
2. Make the changes 
3. Run the tests that are related to the area being changed - watch them pass

For this particular change, @artembilan outlined all the details. I will reiterate and also delve into some more details. 

Basically, the configuration we are currently doing in `HttpRequestFunctionConfiguration`  to create a `WebClient` bean is already being done by [Spring Boot auto-configuration](https://github.com/spring-projects/spring-boot/blob/2.6.x/spring-boot-project/spring-boot-autoconfigure/src/main/java/org/springframework/boot/autoconfigure/web/reactive/function/client/WebClientAutoConfiguration.java). Let's delete our code and let Spring Boot do the work. 

Delete from `HttpRequestFunctionConfiguration`: 
```java
@Bean
@ConditionalOnMissingBean(WebClient.class)
public WebClient webClient(HttpRequestFunctionProperties properties) {
  return WebClient.builder()
      .codecs(clientCodecConfigurer ->
          clientCodecConfigurer.defaultCodecs().maxInMemorySize(properties.getMaximumBufferSize()))
      .build();
}
```
and delete the `maximumBufferSize` from the `HttpRequestFunctionProperties` and things should still work. 

**NOTE:** The http request function is used by the HttpRequestProcessor application (under applications/http-request-procoessor) so you will want to make sure that those tests still pass as well.  

Also, there is a magic file under each app dir that tells users about the configuration options available. See `applications/http-request-procoessor/src/main/resources/dataflow-configuration-metadata.properties`. You will want to add an entry for the WebClient `maximumBufferSize` property so that it gets surfaced in our user docs etc.. You can see how we do similar things in `applications/source/jdbc-source/src/main/resources/META-INF/dataflow-configuration-metadata.properties` for the `spring.datasource.*` properties. 

Ping back when/if you need more clarification or have exact questions once you get started. 

Thanks

**Comment by sunny151091** [comment]
Hi @onobc, 

Thanks for helping me out with my first contribution. 
I have raised a PR for this. Please review it and let me know if any improvements can be made.

**Comment by onobc** [comment]
> Hi @onobc,
> 
> Thanks for helping me out with my first contribution. I have raised a PR for this. Please review it and let me know if any improvements can be made.

Hi @sunny151091 , you are more than welcome. I will review the proposal now. Thanks for the contribution.

**Comment by sunny151091** [comment]
Thanks @onobc and @artembilan for guiding me and reviewing my changes.
