### ISSUE TITLE
Migrate python processor apps to functions

### ISSUE THREAD

**Issue by sobychacko** [spring-cloud/stream-applications#37]
Compose them with httpclient function.

**Comment by dturanski** [comment]
Looking at  existing python based processors that use` jython`.  `Jython 2.7` is the latest release with no definite plans for python 3 support. The problem is python 2.7 is EOL as of 1/1/2020.  Jython also does not support popular native C python libs like `numpy` and `scipy` so limited for real data analytics.  The alternatives all require a local python installation, also Graalvm is an option, and would require a rewrite of these apps.  Another issue with these, is they are designed to download python scripts from git repo at runtime (reuses some  config server classes).  This was done to allow the app to run any python script in a container, but this will not fly in production environments.  The SCDF polyglot support or daisy/knative are likely better options today.  These will be discontinued in  the next `2020.0.0` release.
